### ISSUE TITLE
FileNotFound Error

### ISSUE THREAD

**Issue by xenondev08** [NightFalconX/SomeRandomRepository#1]
In your file Bitcoin_Price_Tracker.py on line 13 you seem to have linked an image on your computer please do add the image to your github repository as the file does not work. Also please use relative imports when you upload projects to gh.

**Comment by NightFalconX** [comment]
Thanks for opening an issue in my BTC_Price_Tracker project! I've updated the code and I've also uploaded the BG picture I used for the project. (Btw it can be used as a sample BG pic)

**Comment by aso6900** [comment]
what's up twats
